### PR TITLE
Show the opponent's name in tag messages

### PR DESCRIPTION
**Pull request by WildWeazel**
This allows players to see and prove who started the fight. Wording is slightly different for victim and attacker, if the attacker is a player.

### CODE REVIEW

**Comment by Techcable** [comment]
Is this tested?

**Comment by WildWeazel** [comment]
Yes, with 1.8. It's just a messaging change.

**Comment by ProgrammerDan** [comment]
Worth noting that I've been running a slightly modified version of this pull for several weeks now; had to address an NPE if one of the attackers is an OP.

See top commit history here: https://github.com/DevotedMC/CombatTagPlus/commits/master (fixed link)

**Comment by ProgrammerDan** [comment]
I have a new version of this waiting on the Civcraft repository, which assumes @Maxopoly 's PR is merged. Reference: https://github.com/Civcraft/CombatTagPlus/tree/master-max-labels

**Comment by Techcable** [comment]
Closed in favor of @ProgrammerDan 's version in b11e22696e8ca4f1ea3c059cb6663ec3c822ee0a

**Pull request closed without merging**
