### PR TITLE
Fixes #85

### LINKED ISSUE #85: Teleporting issue
The operator requested to reopen an issue if the previous issue hasn't been fixed which is the case now.

I am using the latest dev build and the issue is the following:

**While a player is in combat you can't teleport them away with any plugin (Skript, Essentials etc..).**

### PR DESCRIPTION
**Pull request by SpiroMarshes**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
With any luck -- #95 should fix the problem a bit more completely :)

**Comment by christiaanbruijnes** [comment]
That will, ofcourse! When will I be able to download it from the dev builds?

**Comment by ProgrammerDan** [comment]
I'm not sure, if there's no activity on these PRs by the weekend ping me again and I will run a build for you on my build server.

**Comment by Techcable** [comment]
Superseded by #95

**Pull request closed without merging**
