### PR TITLE
Added reconnection timer feature

### PR DESCRIPTION
**Pull request by tomcraft**
This feature prevent players from duplicating inventories with NPC:

When a player has an NPC, with a good reconnection timing he can duplicate his inventories by asking a friend killing the NPC at the exact moment he connect to make drop the NPC's inventory. At this moment, items are on the floor and on the reconnected player's inventory

To fix this I implemented a timer for reconnection.

I made this for my server, but it can be useful for everyone.

### CODE REVIEW

**Comment by Techcable** [comment]
Shouldn't the underlying duplication glitch be fixed?

**Comment by tomcraft** [comment]
There is maybe other solutions, but it was an emergency and I think it's a good feature even if it's not used especially to prevent this glitch.

**Comment by tomcraft** [comment]
I'll fix this in the next commit

**Comment by tomcraft** [comment]
I merged the last commit to resolve conflicts.

**Comment by Techcable** [comment]
So does this fix the glitch without 'use-reconnection-time'?

**Comment by tomcraft** [comment]
My team fails to use the glitch with this build

**Comment by tomcraft** [comment]
I adapted to use as you the Preconditions checks

**Comment by tomcraft** [comment]
No news about this PR ? :/

**Comment by Techcable** [comment]
So will this work if the only change is switching from `PlayerJoinEvent` to `PlayerLoginEvent`?
Is anything else needed?

**Comment by tomcraft** [comment]
Yes it works, but I think the reconnection timer feature is also an interesting feature.

**Comment by tomcraft** [comment]
You must also do theses checks: 

`@EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)`
`public void despawnNpc(PlayerLoginEvent event) {`
`// Do nothing if player can't login`
`if(event.getResult() != Result.ALLOWED) return;`

**Comment by tomcraft** [comment]
So, you really doesn't want to fix your duplication glitch, as you want ^^
Personaly my server is protected against this, it is'nt my problem anymore.

**Pull request closed without merging**
