### PR TITLE
Initial attempt at v1.12 for CTP

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Signed-off-by: ProgrammerDan <programmerdan@gmail.com>

Note this is still pre-6, I'll update this PR once Spigot releases non-dev.

Tested slightly on pre-6, works. You can leverage this immediately using ViaVersion 1.1.1.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Should be g2g. I'll be doing testing on this branch as I get the rest of my plugins up to date and update this PR if any issues arise. If you choose to merge it before I report back, I'll open new PRs with any fixes as they emerge.

**Comment by ProgrammerDan** [comment]
Note I am seeing some config-API related changes that might cause some breaking, I'm digging into it.

**Comment by ProgrammerDan** [comment]
That push fixed it, should be good now.

**Comment by Techcable** [comment]
Just a sec, I have to secretly upload craftbukkit `1.12-R0.1-SNAPSHOT` to my repo or jenkins won't work.
Thanks for doing this update since I forgot 😉

**Comment by ProgrammerDan** [comment]
Happy to help out :D

**Comment by ProgrammerDan** [comment]
~Note that I have reports of no bar, so I'll probably need to check on & update the bar api for folks that use it~

Nevermind, I had it turned off, d'oh!

**Comment by ProgrammerDan** [comment]
@Techcable No new public build yet, much sadness for many? https://ci.minelink.net/ :)

**Pull request merged**
