### PR TITLE
Added player names to tag messages

### PR DESCRIPTION
**Pull request by TealNerd**
Separate tag messages for attacker and victim that can now include
attacker/victim name in message

### CODE REVIEW

**Comment by TealNerd** [comment]
@Sudzzy

**Comment by rourke750** [comment]
@Byteflux Any chance of merge for this?

**Comment by gsand** [comment]
Wouldn't it make more sense to have tagger be attacker and taggee be victim?

**Comment by TealNerd** [comment]
Uh maybe I guess I just didn't think about that

**Comment by Scuwr** [comment]
@gsand What exactly is wrong with this Pull Request? I'd like to fix it.

**Comment by Techcable** [comment]
Closed in favor of @ProgrammerDan 's version by b11e22696e8ca4f1ea3c059cb6663ec3c822ee0a

**Pull request closed without merging**
